# for AWS PIPELINE Build for staging enviornment
version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Node
      - curl -fsSL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - echo Installing source NPM dependencies...
      - cd ant
      - echo `pwd`
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build:stage
  post_build:
    commands:
      # Zip the contents of the build output file
      - tar -cvf build_p.gz build/
      # copy the contents of /build to S3
      - aws s3 cp build_p.gz s3://shenzyn-code/frontend/build_p_stage.gz
artifacts:
  files:
    - '**/*'
  base-directory: build